### ISSUE TITLE
embedded still fails sometimes using my brute force test

### ISSUE THREAD

**Issue by cameronbraid** [sunshower-io/zephyr#173]
```
git clone https://github.com/cameronbraid/zephyr-embedded-demo
cd zephyr-embedded-demo
git checkout brute-force-startup
./verify.sh
```

The two errors I have produced are :

```
May 28, 2022 7:15:38 PM io.zephyr.kernel.core.actions.ModuleDownloadPhase fireDownloadFailed
SEVERE: Error downloading module from 'file:/workspace/zephyr-embedded-demo/zephyr/target/plugins/zephyr-embedded-demo-plugin.war'.  Reason: io.zephyr.kernel.concurrency.TaskException: Error creating directory '/tmp/zephyr4273950515230539941/kernel/downloads'.  Directory does not exist and cannot be created
io.zephyr.kernel.concurrency.TaskException: Error creating directory '/tmp/zephyr4273950515230539941/kernel/downloads'.  Directory does not exist and cannot be created
        at io.zephyr.kernel.core.actions.ModuleDownloadPhase.getTargetDirectory(ModuleDownloadPhase.java:94)
        at io.zephyr.kernel.core.actions.ModuleDownloadPhase.downloadModule(ModuleDownloadPhase.java:81)
        at io.zephyr.kernel.core.actions.ModuleDownloadPhase.run(ModuleDownloadPhase.java:55)
        at io.zephyr.kernel.concurrency.TopologyAwareParallelScheduler$NotifyingTask.call(TopologyAwareParallelScheduler.java:72)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

and

```

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running drivenow.zephyrdemo.zephyr.ZephyrTest
May 28, 2022 7:16:32 PM io.zephyr.kernel.core.DefaultModuleManager initialize
INFO: Initializing Module Manager 'io.zephyr.kernel.core.DefaultModuleManager@2f953efd' with kernel 'io.zephyr.kernel.core.SunshowerKernel@d2de489'
May 28, 2022 7:16:32 PM io.zephyr.kernel.core.DefaultModuleManager initialize
INFO: Finished initializing Module Manager 'io.zephyr.kernel.core.DefaultModuleManager@2f953efd' with kernel 'io.zephyr.kernel.core.SunshowerKernel@d2de489'
May 28, 2022 7:16:32 PM io.zephyr.kernel.concurrency.TopologyAwareParallelScheduler submit
INFO: scheduling new execution graph 'Process(name=kernel:start:filesystem, coalesce paths=false, parallel=false)'
May 28, 2022 7:16:32 PM io.zephyr.kernel.concurrency.TopologyAwareParallelScheduler submit
INFO: successfully scheduled new execution graph 'Process(name=kernel:start:filesystem, coalesce paths=false, parallel=false)'
May 28, 2022 7:16:32 PM io.zephyr.kernel.core.lifecycle.KernelFilesystemCreatePhase run
INFO: Attempting to create Kernel filesystem
May 28, 2022 7:16:32 PM io.zephyr.kernel.launch.KernelOptions resolveRoot
INFO: Attempting to resolve file system root from system properties, key "zephyr.options.home"
May 28, 2022 7:16:32 PM io.zephyr.kernel.launch.KernelOptions resolveRoot
INFO: System property ''{0}'' is not set.  Checking for ZEPHYR_HOME in environment variables
May 28, 2022 7:16:32 PM io.zephyr.kernel.launch.KernelOptions resolveRoot
INFO: ENV VARIABLE ''{0}'' is not set.  Attempting resolution from options
May 28, 2022 7:16:32 PM io.zephyr.kernel.core.lifecycle.KernelFilesystemCreatePhase run
INFO: Created Kernel Filesystem at '[/tmp/zephyr6480305034723974787/kernel]'
May 28, 2022 7:16:32 PM io.zephyr.kernel.module.ModuleListParser resolveModuleFile
INFO: Module file 'droplet://kernel/module.list' at physical location '/tmp/zephyr6480305034723974787/kernel/modules.list' does not exist--attempting to create...
May 28, 2022 7:16:32 PM io.zephyr.kernel.module.ModuleListParser resolveModuleFile
INFO: Succeeded in creating module file 'droplet://kernel/module.list' at physical location '/tmp/zephyr6480305034723974787/kernel/modules.list' does not exist--attempting to create...
May 28, 2022 7:16:32 PM io.zephyr.kernel.concurrency.TopologyAwareParallelScheduler submit
INFO: scheduling new execution graph 'Process(name=kernel:module:load, coalesce paths=false, parallel=false)'
May 28, 2022 7:16:32 PM io.zephyr.kernel.concurrency.TopologyAwareParallelScheduler submit
INFO: successfully scheduled new execution graph 'Process(name=kernel:module:load, coalesce paths=false, parallel=false)'
May 28, 2022 7:16:32 PM io.zephyr.kernel.core.Modules handleKernelModules
INFO: Installation request contained no (valid) plugins--not doing anything
May 28, 2022 7:16:32 PM io.zephyr.kernel.concurrency.TopologyAwareParallelScheduler submit
INFO: scheduling new execution graph 'Process(name=module:lifecycle:change, coalesce paths=true, parallel=true)'
May 28, 2022 7:16:32 PM io.zephyr.kernel.concurrency.TopologyAwareParallelScheduler submit
INFO: successfully scheduled new execution graph 'Process(name=module:lifecycle:change, coalesce paths=true, parallel=true)'
May 28, 2022 7:16:32 PM io.zephyr.kernel.concurrency.TopologyAwareParallelScheduler submit
INFO: scheduling new execution graph 'Process(name=module:install, coalesce paths=true, parallel=true)'
May 28, 2022 7:16:32 PM io.zephyr.kernel.concurrency.TopologyAwareParallelScheduler submit
INFO: successfully scheduled new execution graph 'Process(name=module:install, coalesce paths=true, parallel=true)'
May 28, 2022 7:16:32 PM io.zephyr.kernel.core.actions.ModuleDownloadPhase getTargetDirectory
INFO: Creating Module Download target directory '/tmp/zephyr6480305034723974787/kernel/downloads'
May 28, 2022 7:16:32 PM io.zephyr.kernel.core.actions.ModuleDownloadPhase getTargetDirectory
INFO: Creating Module Download target directory '/tmp/zephyr6480305034723974787/kernel/downloads'
May 28, 2022 7:16:32 PM io.zephyr.kernel.core.actions.ModuleDownloadPhase downloadModule
INFO: Beginning Module Download from 'file:/tmp/plugin-15226753156716860442.jar' to '/tmp/zephyr6480305034723974787/kernel/downloads'
May 28, 2022 7:16:32 PM io.zephyr.kernel.core.actions.ModuleDownloadPhase downloadModule
INFO: Beginning Module Download from 'file:/workspace/zephyr-embedded-demo/zephyr/target/plugins/zephyr-embedded-demo-plugin.war' to '/tmp/zephyr6480305034723974787/kernel/downloads'
May 28, 2022 7:16:32 PM io.zephyr.kernel.launch.KernelOptions resolveRoot
INFO: Attempting to resolve file system root from system properties, key "zephyr.options.home"
May 28, 2022 7:16:32 PM io.zephyr.kernel.launch.KernelOptions resolveRoot
INFO: System property ''{0}'' is not set.  Checking for ZEPHYR_HOME in environment variables
May 28, 2022 7:16:32 PM io.zephyr.kernel.launch.KernelOptions resolveRoot
INFO: ENV VARIABLE ''{0}'' is not set.  Attempting resolution from options
May 28, 2022 7:16:32 PM io.zephyr.kernel.core.actions.ModuleTransferPhase createFilesystem
INFO: Attempting to create module filesystem under 'droplet://drivenow.zephyr-embedded-demo-api?version=0.0.0'
May 28, 2022 7:16:32 PM io.zephyr.kernel.core.actions.ModuleTransferPhase createFilesystem
INFO: Successfully created filesystem 'droplet://drivenow.zephyr-embedded-demo-api?version=0.0.0' at physical location '/tmp/zephyr6480305034723974787/drivenow/zephyr-embedded-demo-api/0.0.0'
May 28, 2022 7:16:32 PM io.zephyr.kernel.core.actions.ModuleTransferPhase run
INFO: Copying file '/tmp/zephyr6480305034723974787/kernel/downloads/plugin-15226753156716860442.jar' to '/tmp/zephyr6480305034723974787/drivenow/zephyr-embedded-demo-api/0.0.0/module.droplet'...
May 28, 2022 7:16:32 PM io.zephyr.kernel.core.actions.ModuleTransferPhase run
INFO: Successfully copied file '/tmp/zephyr6480305034723974787/kernel/downloads/plugin-15226753156716860442.jar' to '/tmp/zephyr6480305034723974787/drivenow/zephyr-embedded-demo-api/0.0.0/module.droplet'
May 28, 2022 7:16:32 PM io.zephyr.kernel.core.actions.ModuleTransferPhase createFilesystem
INFO: Attempting to create module filesystem under 'droplet://drivenow.zephyr-embedded-demo-plugin?version=0.0.0'
May 28, 2022 7:16:32 PM io.zephyr.kernel.core.actions.ModuleTransferPhase createFilesystem
INFO: Successfully created filesystem 'droplet://drivenow.zephyr-embedded-demo-plugin?version=0.0.0' at physical location '/tmp/zephyr6480305034723974787/drivenow/zephyr-embedded-demo-plugin/0.0.0'
May 28, 2022 7:16:32 PM io.zephyr.kernel.core.actions.ModuleTransferPhase run
INFO: Copying file '/tmp/zephyr6480305034723974787/kernel/downloads/zephyr-embedded-demo-plugin.war' to '/tmp/zephyr6480305034723974787/drivenow/zephyr-embedded-demo-plugin/0.0.0/module.droplet'...
May 28, 2022 7:16:32 PM io.zephyr.kernel.core.actions.ModuleTransferPhase run
INFO: Successfully copied file '/tmp/zephyr6480305034723974787/kernel/downloads/zephyr-embedded-demo-plugin.war' to '/tmp/zephyr6480305034723974787/drivenow/zephyr-embedded-demo-plugin/0.0.0/module.droplet'
May 28, 2022 7:16:32 PM io.zephyr.kernel.module.AbstractCompressedModuleAssemblyExtractor createArchive
INFO: Extracting file '/tmp/zephyr6480305034723974787/drivenow/zephyr-embedded-demo-plugin/0.0.0/module.droplet'
May 28, 2022 7:16:32 PM io.zephyr.kernel.module.AbstractCompressedModuleAssemblyExtractor createArchive
INFO: Extracting file '/tmp/zephyr6480305034723974787/drivenow/zephyr-embedded-demo-api/0.0.0/module.droplet'
May 28, 2022 7:16:32 PM io.zephyr.kernel.module.AbstractCompressedModuleAssemblyExtractor createArchive
INFO: Extracting file '/tmp/zephyr6480305034723974787/drivenow/zephyr-embedded-demo-api/0.0.0/module.droplet'
May 28, 2022 7:16:32 PM io.zephyr.kernel.core.actions.ModuleUnpackPhase run
INFO: Applying extractor 'io.zephyr.kernel.module.WarModuleAssemblyExtractor@511311ee'...
May 28, 2022 7:16:32 PM io.zephyr.kernel.module.AbstractCompressedModuleAssemblyExtractor createArchive
INFO: Extracting file '/tmp/zephyr6480305034723974787/drivenow/zephyr-embedded-demo-plugin/0.0.0/module.droplet'
May 28, 2022 7:16:32 PM io.zephyr.kernel.core.actions.ModuleUnpackPhase run
INFO: Applying extractor 'io.zephyr.kernel.module.DefaultJarModuleAssemblyExtractor@1f18bb9a'...
May 28, 2022 7:16:32 PM io.zephyr.kernel.module.AbstractCompressedModuleAssemblyExtractor createArchive
INFO: Extracting file '/tmp/zephyr6480305034723974787/drivenow/zephyr-embedded-demo-api/0.0.0/module.droplet'
May 28, 2022 7:16:33 PM io.zephyr.kernel.core.actions.ModuleUnpackPhase run
INFO: Successfully applied extractor 'io.zephyr.kernel.module.DefaultJarModuleAssemblyExtractor@1f18bb9a'
May 28, 2022 7:16:33 PM io.zephyr.kernel.core.actions.ModuleUnpackPhase run
INFO: Successfully applied extractor 'io.zephyr.kernel.module.WarModuleAssemblyExtractor@511311ee'
May 28, 2022 7:16:33 PM io.zephyr.kernel.core.actions.WriteKernelModuleListPhase run
INFO: no descriptors found
May 28, 2022 7:16:33 PM io.zephyr.kernel.core.Modules handleKernelModules
INFO: Installation request contained no (valid) plugins--not doing anything
May 28, 2022 7:16:33 PM io.zephyr.kernel.core.Modules performInstallation
INFO: Installation request scheduled 1 plugins for installation
May 28, 2022 7:16:33 PM io.zephyr.kernel.core.Modules performInstallation
INFO: Attempting to RESOLVE all plugins
May 28, 2022 7:16:33 PM io.zephyr.kernel.core.Modules checkForUnresolvedDependencies
WARNING: Detected unresolved dependencies--not continuing
May 28, 2022 7:16:33 PM io.zephyr.kernel.concurrency.TopologyAwareParallelScheduler$NotifyingTask call
INFO: Error processing task module:kernel:install:plugins
io.zephyr.kernel.dependencies.UnresolvedDependencyException: unresolved dependencies detected 
        unresolved dependencies: 
        drivenow:zephyr-embedded-demo-plugin:0.0.0 depends on [group=drivenow:name=zephyr-embedded-demo-api:version=0.0.0]

        at io.zephyr.kernel.core.Modules.checkForUnresolvedDependencies(Modules.java:302)
        at io.zephyr.kernel.core.Modules.performInstallation(Modules.java:172)
        at io.zephyr.kernel.core.actions.WritePluginDescriptorPhase.run(WritePluginDescriptorPhase.java:31)
        at io.zephyr.kernel.concurrency.TopologyAwareParallelScheduler$NotifyingTask.call(TopologyAwareParallelScheduler.java:72)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

May 28, 2022 7:16:33 PM io.zephyr.kernel.concurrency.TopologyAwareParallelScheduler submit
INFO: scheduling new execution graph 'Process(name=module:lifecycle:change, coalesce paths=true, parallel=true)'
May 28, 2022 7:16:33 PM io.zephyr.kernel.concurrency.TopologyAwareParallelScheduler submit
INFO: successfully scheduled new execution graph 'Process(name=module:lifecycle:change, coalesce paths=true, parallel=true)'
```

**Comment by josiahhaswell** [comment]
Fixed and released in 2.0.128
